# Generated by Django 2.0.7 on 2019-02-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='bcc',
            new_name='email_to',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='emailid_from',
        ),
        migrations.RemoveField(
            model_name='email',
            name='emailid_to',
        ),
    ]
