# Generated by Django 2.0.7 on 2019-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20190211_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
