# Generated by Django 2.0.7 on 2019-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20190218_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_to',
            field=models.CharField(max_length=120),
        ),
    ]
