# Generated by Django 2.0.7 on 2019-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20190218_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='admin@mailservice.com', max_length=254),
            preserve_default=False,
        ),
    ]
